# Temporary ruff configuration to relax rules and unblock CI while we iteratively fix code quality issues.
# Use top-level keys (no [tool.ruff] header) because .ruff.toml expects top-level configuration.
extend-ignore = [
  "C901",  # complexity (functions too complex)
  "N806",  # variable in function should be lowercase
  "F841",  # assigned but unused
  "E501",  # line too long
  "C401",  # unnecessary generator (suggest set comp)
  "E741",  # ambiguous variable name like 'l'
  "F401",  # unused imports
  "F811",  # redefinition
  "N801",  # naming conventions in typings
  "N802",  # function name should be lowercase in typings
]

# Exclude generated / third-party typing stubs from strict linting
exclude = [
  "typings/**",
  "build/**",
  "public/**",
]
