from typing import Any, Tuple, Iterable

def array(*args: Any, **kwargs: Any) -> Any: ...
def ndarray(*args: Any, **kwargs: Any) -> Any: ...

class ndarray: ...

def mean(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def zeros(shape: Iterable[int], *args: Any, **kwargs: Any) -> Any: ...
